/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import bd.*;
import modelo.*;
import controlador.*;
import java.sql.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import jdk.nashorn.internal.objects.NativeArray;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author juanr
 */
public class Listar extends javax.swing.JFrame {

    /**
     * Creates new form Listar
     */
    public Listar() {
        initComponents();
    }
    ArrayList<Cliente> listaCliente = new ArrayList();
    ArrayList<Tecnico> listaTecnico = new ArrayList();

    void mostrarDatos(int filtro, String run) {
        if (filtro == 1) {
            DefaultTableModel modelo = new DefaultTableModel();
            modelo.addColumn("Run");
            modelo.addColumn("Nombre");
            modelo.addColumn("Apellido");
            modelo.addColumn("Email");
            modelo.addColumn("Direccion");
            modelo.addColumn("Fono");
            modelo.addColumn("Password");
            tbLista.setModel(modelo);
            String[] datos = new String[7];
            for (int i = 0; i < listaCliente.size(); i++) {
                if (listaCliente.get(i).getRun().equals(run)) {
                    datos[0] = listaCliente.get(i).getRun();
                    datos[1] = listaCliente.get(i).getNombre();
                    datos[2] = listaCliente.get(i).getApellido();
                    datos[3] = listaCliente.get(i).getEmail();
                    datos[4] = listaCliente.get(i).getDireccion();
                    datos[5] = listaCliente.get(i).getFono();
                    datos[6] = listaCliente.get(i).getPassword();
                    modelo.addRow(datos);
                }
            }
        } else {
            DefaultTableModel modelo = new DefaultTableModel();
            modelo.addColumn("Run");
            modelo.addColumn("Nombre");
            modelo.addColumn("Apellido");
            modelo.addColumn("Email");
            modelo.addColumn("HorarioTrabajo");
            modelo.addColumn("Fono");
            modelo.addColumn("Password");
            tbLista.setModel(modelo);
            String[] datos = new String[7];
            for (int i = 0; i < listaTecnico.size(); i++) {
                if (listaTecnico.get(i).getRun().equals(run)) {
                    datos[0] = listaTecnico.get(i).getRun();
                    datos[1] = listaTecnico.get(i).getNombre();
                    datos[2] = listaTecnico.get(i).getApellido();
                    datos[3] = listaTecnico.get(i).getEmail();
                    datos[4] = listaTecnico.get(i).getHorarioTrabajo();
                    datos[5] = listaTecnico.get(i).getFono();
                    datos[6] = listaTecnico.get(i).getPassword();
                    modelo.addRow(datos);
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lista = new javax.swing.ButtonGroup();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        Eliminar = new javax.swing.JMenuItem();
        modificar = new javax.swing.JMenuItem();
        panel1 = new java.awt.Panel();
        Cliente = new javax.swing.JRadioButton();
        Tecnico = new javax.swing.JRadioButton();
        txtRun = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Buscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbLista = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        Eliminar.setText("Eliminar");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });
        jPopupMenu1.add(Eliminar);

        modificar.setText("Modificar");
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });
        jPopupMenu1.add(modificar);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lista.add(Cliente);
        Cliente.setSelected(true);
        Cliente.setText("Cliente");

        lista.add(Tecnico);
        Tecnico.setText("Tecnico");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Cliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Tecnico)
                .addGap(0, 8, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cliente)
                    .addComponent(Tecnico))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setText("Run");

        Buscar.setText("Buscar");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });

        tbLista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbLista.setComponentPopupMenu(jPopupMenu1);
        jScrollPane1.setViewportView(tbLista);

        jButton1.setText("Agregar Cliente");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Agregar Tecnico");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtRun, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Buscar))
                            .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(jButton1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(Buscar)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(184, 184, 184))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        // TODO add your handling code here:
        String run = txtRun.getText();
        int filtro;
        if (this.Cliente.isSelected()) {
            filtro = 1;
        } else {
            filtro = 2;
        }
        mostrarDatos(filtro, run);
    }//GEN-LAST:event_BuscarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        agregarcli();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        agregarTec();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        String run = tbLista.getValueAt(tbLista.getSelectedRow(), 0).toString();
        if (this.Cliente.isSelected()) {
            for (int i = 0; i < listaCliente.size(); i++) {
                if (run == listaCliente.get(i).getRun()) {
                    listaCliente.remove(i);
                }
            }
        } else {
            for (int i = 0; i < listaTecnico.size(); i++) {
                if (run == listaTecnico.get(i).getRun()) {
                    listaTecnico.remove(i);
                }
            }
        }
    }//GEN-LAST:event_EliminarActionPerformed

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
        String run = tbLista.getValueAt(tbLista.getSelectedRow(), 0).toString();
        if (this.Cliente.isSelected()) {
            for (int i = 0; i < listaCliente.size(); i++) {
                if (run == listaCliente.get(i).getRun()) {
                    boolean l = agregarcli();
                    if (l) {
                        listaCliente.remove(i);
                    }else{
                    
                    }
                    
                }
            }
        } else {
            for (int i = 0; i < listaTecnico.size(); i++) {
                if (run == listaTecnico.get(i).getRun()) {
                    boolean a = agregarTec();
                    if (a){
                        listaTecnico.remove(i);
                    }
                    
                }
            }
        }
    }//GEN-LAST:event_modificarActionPerformed
    public static boolean validarRut(String rut) {

        boolean validacion = false;
        try {
            rut = rut.toUpperCase();
            rut = rut.replace(".", "");
            rut = rut.replace("-", "");
            int rutAux = Integer.parseInt(rut.substring(0, rut.length() - 1));

            char dv = rut.charAt(rut.length() - 1);

            int m = 0, s = 1;
            for (; rutAux != 0; rutAux /= 10) {
                s = (s + rutAux % 10 * (9 - m++ % 6)) % 11;
            }
            if (dv == (char) (s != 0 ? s + 47 : 75)) {
                validacion = true;
            }

        } catch (java.lang.NumberFormatException e) {
        } catch (Exception e) {
        }
        return validacion;
    }
    
    public boolean agregarcli(){
        Cliente clienteADD = new Cliente();
        JTextField f1 = new JTextField();
        JTextField f2 = new JTextField();
        JTextField f3 = new JTextField();
        JTextField f4 = new JTextField();
        JTextField f5 = new JTextField();
        JTextField f6 = new JTextField();
        JTextField f7 = new JTextField();

        Object[] fields = {
            "Nombre", f1,
            "Apellido", f2,
            "Run", f3,
            "Fono", f4,
            "Direccion", f5,
            "Email", f6,
            "Password", f7,};
        JOptionPane.showConfirmDialog(null, fields, "Agregar Cliente", JOptionPane.OK_CANCEL_OPTION);
        clienteADD.setNombre(f1.getText());
        clienteADD.setApellido(f2.getText());
        clienteADD.setRun(f3.getText());
        clienteADD.setFono(f4.getText());
        clienteADD.setDireccion(f5.getText());
        clienteADD.setEmail(f6.getText());
        clienteADD.setPassword(f7.getText());

        if (validarRut(clienteADD.getRun())) {
            listaCliente.add(clienteADD);
            JOptionPane.showMessageDialog(null, "Cliente agregado");
            return true;
        } else {
            JOptionPane.showMessageDialog(null, "Run incorrecto");
            return false;
        }
    }
    
    public boolean agregarTec (){
        Tecnico tecnicoADD = new Tecnico();
        JTextField f1 = new JTextField();
        JTextField f2 = new JTextField();
        JTextField f3 = new JTextField();
        JTextField f4 = new JTextField();
        JTextField f5 = new JTextField();
        JTextField f6 = new JTextField();
        JTextField f7 = new JTextField();

        Object[] fields = {
            "Nombre", f1,
            "Apellido", f2,
            "Run", f3,
            "Fono", f4,
            "HorarioTrabajo", f5,
            "Email", f6,
            "Password", f7,};
        JOptionPane.showConfirmDialog(null, fields, "Agregar Tecnico", JOptionPane.OK_CANCEL_OPTION);
        tecnicoADD.setNombre(f1.getText());
        tecnicoADD.setApellido(f2.getText());
        tecnicoADD.setRun(f3.getText());
        tecnicoADD.setFono(f4.getText());
        tecnicoADD.setHorarioTrabajo(f5.getText());
        tecnicoADD.setEmail(f6.getText());
        tecnicoADD.setPassword(f7.getText());
        if (validarRut(tecnicoADD.getRun())) {
            listaTecnico.add(tecnicoADD);
            JOptionPane.showMessageDialog(null, "Tecnico agregado");
            return true;
        } else {
            JOptionPane.showMessageDialog(null, "Run incorrecto");
            return false;
        }
    }
            

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Listar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Listar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Listar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Listar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Listar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buscar;
    private javax.swing.JRadioButton Cliente;
    private javax.swing.JMenuItem Eliminar;
    private javax.swing.JRadioButton Tecnico;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.ButtonGroup lista;
    private javax.swing.JMenuItem modificar;
    private java.awt.Panel panel1;
    private javax.swing.JTable tbLista;
    private javax.swing.JTextField txtRun;
    // End of variables declaration//GEN-END:variables
}
